dataset:
  train:
    image: "/home/vice-calibras/mus_brain_seg/data/mouse_brain_unet_dataset/train/JPEGImages"
    mask: "/home/vice-calibras/mus_brain_seg/data/mouse_brain_unet_dataset/train/SegmentationClass"
  test:
    image: "/home/vice-calibras/mus_brain_seg/data/mouse_brain_unet_dataset/test/JPEGImages"
    mask: "/home/vice-calibras/mus_brain_seg/data/mouse_brain_unet_dataset/test/SegmentationClass"
seed: 42
output_size: 128
batch_size: 8
epochs: 10
lr: 0.001
